+ blocking io, wait_event_interruptible

diff --git a/ldt-test b/ldt-test
--- a/ldt-test
+++ b/ldt-test
@@ -11,6 +11,7 @@
 RED="\\033[0;31m"
 NOCOLOR="\\033[0;39m"
 GREEN="\\033[0;32m"
+GRAY="\\033[0;37m"
 
 set -o errtrace
 tracing=/sys/kernel/debug/tracing
@@ -53,13 +54,30 @@ tracing_start || true
 id=`grep -w ldt /proc/misc | cut -c -3`
 sudo sh -c "rm /dev/ldt;sudo mknod /dev/ldt c 10 $id; chmod o+rw /dev/ldt"
 data=123rw
-echo $data > /dev/ldt
+echo -n $data > /dev/ldt
 sleep 0.5
-received=`head -n 1 /dev/ldt`
+received=`dd iflag=nonblock if=/dev/ldt 2> /dev/null || true`
 if [ "$data" == "$received" ]; then
-echo -e "${GREEN}LDT read/write test passed$NOCOLOR"
+echo -e "${GREEN}LDT nonblocking read/write test passed$NOCOLOR"
 else
-echo -e "${RED}LDT read/write test failed$NOCOLOR"
+echo -e "${RED}LDT nonblock read/write test failed$NOCOLOR"
+echo expected $data
+echo received $received
+fi
+
+data=123bl
+cat /dev/ldt > R.tmp &
+sleep 0.5; echo -n $data > /dev/ldt;
+sleep 0.5
+kill %1; wait %1 2> /dev/null || true
+received=`cat R.tmp`
+
+if [ "$data" == "$received" ]; then
+echo -e "${GREEN}LDT blocking read/write test passed$NOCOLOR"
+else
+echo -e "${RED}LDT blocking read/write test failed$NOCOLOR"
+echo expected $data
+echo received $received
 fi
 
 data=123mmap
